import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import "../assets/fonts/index.css";
import AosAnimation from "@/components/layout/aos-animation";

export const metadata = {
  title: "UpLinke",
  description: "Generated by UpLinke",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <AosAnimation>
          <Header />
          {children}
          <Footer />
        </AosAnimation>
      </body>
    </html>
  );
}
